const controllerCoverProduct = [
  {
    img: "https://m.media-amazon.com/images/I/71u8Va3jfUL._AC_SX296_SY426_FMwebp_QL65_.jpg",
    name: "eXtremeRate PlayVital Anti-slip Silicone Protective Case for PS5 Controller, Cover Skin Grip for PS5, Protective Skins Case Protector for PS5 with Thumb Grip Caps - Wine Red (Samurai Edition)",
    price: 1500000,
    id: "controllerCover-extreamrate",
    cat: "controllerCover",
    isClicked: false,
    amount: 0,
    section: "accessory",
    platform: "console",
  },
  {
    img: "https://m.media-amazon.com/images/I/61rYcWAg+XL._AC_SX296_SY426_FMwebp_QL65_.jpg",
    name: "PlayVital Controller Silicone Case for PS5,Controller Skin for PS5 with Thumb Grip Caps & Touch Pad Sticker,Cute Demon Non-Slip Silicone Cover Protective Case for PS5 Controller-Purple",
    price: 1500000,
    id: "controllerCover-playvital",
    cat: "controllerCover",
    isClicked: false,
    amount: 0,
    section: "accessory",
    platform: "console",
  },
  {
    img: "https://m.media-amazon.com/images/I/61-TlF3S2gL._AC_SX148_SY213_QL70_.jpg",
    name: "HLRAO PS4 Controller Skin Pink, Non-Slip Grip Silicone Cover Protective Case Compatible for PS4/Slim/Pro Wireless/Wired Gamepad Controller with 8 x FPS Pro Thumb Grip Caps + 2 Cat Paw Caps.",
    price: 1500000,
    id: "controllerCover-logitech-b100",
    cat: "controllerCover",
    isClicked: false,
    amount: 0,
    section: "accessory",
    platform: "console",
  },
];
export default controllerCoverProduct;
