const keyboardProduct = [
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/618zZ7u3sUL._AC_SX679_.jpg",
    name: "MageGee Portable 60% Mechanical Gaming Keyboard, MK-Box LED Backlit Compact 68 Keys Mini Wired Office Keyboard with Red Switch for Windows Laptop PC Mac - Black/Grey",
    price: 1500000,
    id: "keyboard-MageGee-black/gray",
    cat: "keyboard",
    isClicked: false,
    amount: 0,
    section: "accessory",
    platform: "pc",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/61hdRFcTkzL._AC_SX679_.jpg",
    name: "HITIME XVX M61 60% Mechanical Keyboard Wireless, Ultra-Compact 2.4G Rechargeable Gaming Keyboard, RGB Backlit Ergonomic Keyboard for Windows Mac PC Gamers(Coral Sea Theme, Gateron Yellow Switch)",
    price: 3500000,
    id: "keyboard-Hitime",
    cat: "keyboard",
    isClicked: false,
    amount: 0,
    section: "accessory",
    platform: "pc",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/71NMtTQkYUL._AC_SX679_.jpg",
    name: "MageGee Portable 60% Mechanical Gaming Keyboard, MK-Box LED Backlit Compact 68 Keys Mini Wired Office Keyboard with Blue Switch for Windows Laptop PC Mac - Grey/Black",
    price: 1500000,
    id: "keyboard-MageGee-grey/black",
    cat: "keyboard",
    isClicked: false,
    amount: 0,
    section: "accessory",
    platform: "pc",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/71T9LY+8YoL._AC_SY300_SX300_.jpg",
    name: "Ussixchare 60 Percent Mechanical Keyboard Mini Gaming Keyboard 60% with Red Switch Wired Type-C Cable Mini Keyboard with LED Backlight for Laptop/PC/Mac/PS5/PS4/Xbox Gamer(White-Black)",
    price: 1500000,
    id: "keyboard-Ussoxchare",
    cat: "keyboard",
    isClicked: false,
    amount: 0,
    section: "accessory",
    platform: "pc",
  },
];
export default keyboardProduct;
