const nintendoProducts = [
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/71cj5cNm7ZL._AC_UY218_.jpg",
    name: "nintendo gift card 20$",
    price: 50000,
    id: "nintendo-20",
    cat: "nintendo",
    isClicked: false,
    amount: 0,
    section: "giftcard",
    platform: "console",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/61EYYBkMUJL._AC_UY218_.jpg",
    name: "nintendo gift card 35$",
    price: 200000,
    id: "nintendo-35",
    cat: "nintendo",
    isClicked: false,
    amount: 0,
    section: "giftcard",
    platform: "console",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/613kqR4NErL._AC_UY218_.jpg",
    name: "nintendo gift card 45$",
    price: 300000,
    id: "nintendo-45",
    cat: "nintendo",
    isClicked: false,
    amount: 0,
    section: "giftcard",
    platform: "console",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/611cS6qGPeL._AC_UY218_.jpg",
    name: "nintendo gift card 99$",
    price: 300000,
    id: "nintendo-99",
    cat: "nintendo",
    isClicked: false,
    amount: 0,
    section: "giftcard",
    platform: "console",
  },
];

export default nintendoProducts;
